export const SITE_SET_TITLE = 'SITE_SET_TITLE';

export const TODO_ITEM_ADD = 'TODO_ITEM_ADD'; 
export const TODO_ITEM_REMOVE = 'TODO_ITEM_REMOVE';
export const TODO_ITEM_EDIT = 'TODO_ITEM_EDIT';
export const TODO_ITEM_UPDATE = 'TODO_ITEM_UPDATE';